sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;   #going to download google cloud SDK and install it locally on our instance for travis CI.
  - source $HOME:google-cloud-sdk/path.bash.inc             #look at the default install directory of google cloud SDK, and source the file path.bash.inc.
  - gcloud components update kubectl                        #Install kubectk command.
  - gcloud auth activate-sercice-account --key-file sercice-account.json    #autorisations to login 
